name: Deploy Node app

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2

      - name: gcloud authentication docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: build the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: docker build -t europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/dockerize-node-app/test-image:latest ./app

      - name: push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: docker push europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/dockerize-node-app/test-image:latest

      - name: deploy on cloud run
        run: gcloud run deploy ${{ env.GCLOUD_RUN_SERVICE }} --image=europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/dockerize-node-app/test-image:latest --region=europe-west1 --project=$GOOGLE_PROJECT --allow-unauthenticated
        env:
          GCLOUD_RUN_SERVICE: expose-node-app
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
